# Generated by Django 3.1.4 on 2021-01-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='num2',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
